### ISSUE TITLE
Need Join Message

### ISSUE THREAD

**Issue by Edwardthedog2** [EndKingdom/SAM#1]
I need help making it to where the player receives a join message, when they first join the game. The message for unregistered users will be: "This server uses SAM by Edwardthedog2. You must register at (servers website URL) to play", and the join message for registered users to be: "To play you must login with /login (your password)."

**Comment by HittmanA** [comment]
I can do a piece of code that sends a message when they join the server. Is that ok? I can also (maybe) add the different registered and not messages. Let me know if you want this!

**Comment by Edwardthedog2** [comment]
Yes, that would be wonderful.

**Comment by HittmanA** [comment]
Great! I will get to work as soon as I can!

**Comment by HittmanA** [comment]
Ok I am finished. Do you need the plugin.yml and an explanation of the code or can you figure it out.

**Comment by Edwardthedog2** [comment]
I might be able to figure it out eventually, but an explanation would be nice, yeah.

**Comment by HittmanA** [comment]
Ok https://github.com/HittmanA/SAM--join-messages is the repo. Go to the wiki for the explanation and let me know if you need more help!

**Comment by Edwardthedog2** [comment]
Okay, thank you.
