### ISSUE TITLE
chatlogin

### ISSUE THREAD

**Issue by Driesboy** [EndKingdom/SAM#3]

**Comment by Edwardthedog2** [comment]
Yes I will add the code to login from chat, as soon as I get home.

**Comment by Edwardthedog2** [comment]
Okay, I have completed, not sure if it works though.

**Comment by HittmanA** [comment]
Need my help with anything else?

**Comment by Edwardthedog2** [comment]
Yes, for some reason the join message doesn't  appear.

**Comment by HittmanA** [comment]
You have to have $registered set as TRUE or FALSE for it to work
